plugins:
  swarm:
    executor: central_deployment_agent
    source: cloudify-swarm-plugin

node_types:
      
  ###################################################################
  # Represents a master/node, for use if not using deployment proxy
  ###################################################################
  cloudify.swarm.Manager:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      ip:
        description: ip address of the manager to connect to
      port:
        description: manager port
        default: 2375
      ssh_user:
        description: used for operations requiring cli access (e.g. Compose)
        default: ''
      ssh_keyfile:
        description: private key used for operations requiring cli access (e.g. Compose)
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        create: swarm.swarm_plugin.tasks.connect_manager
        

  ##########################################
  # Represents a swarm microservice
  # 
  # See REST API for config details.
  #   camel case replaced with _ (e.g. RestartPolicy => restart_policy)
  #
  ##########################################
  cloudify.swarm.Microservice:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      name:
        description: the name of the service
        type: string
      labels:
        default: {}
        # key: value
      task_template:
        default: {}
        # container_spec:
        #   image: nginx:alpine
        #   mounts:
        #     read_only: true
        #     source: "web-data"
        #     target: "/usr/share/nginx/html"
        #     type: volume
        #     volume_options:
        #       driver_config:
        #     labels:
        #       key: val
        #   user: 33
        # log_driver:
        #   name: json-file
        #   options:
        #     max-file: 3
        #     max-size: 10M
        # placement:
        #   - constraint1
        #   - constraint2
        # resources:
        #   limits:
        #     memory_bytes: 102031202
        #   reservations
        #     nano_cpus: 1231212333
        # restart_policy:
        #   condition: on-failure
        #   delay: 10000000000.0
        #   max_attempts: 10
      mode: 
        default:
          replicated:
            replicas: 1
      update_config:
        default: {}
        # delay: 300000000.0
        # parallelism: 2
        # failure_action: pause
      networks:
        default: []
      endpoint_spec:
        default: {}
        # ports:
        #   protocol: tcp
        #   published_port: 80
        #   target_port: 80
      compose_file:
        description: a compose file to use.  If set, other properties are ignored
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        start: swarm.swarm_plugin.tasks.start_service
        delete: swarm.swarm_plugin.tasks.rm_service


relationships:

  cloudify.swarm.relationships.microservice_contained_in_manager:
    derived_from: cloudify.relationships.contained_in
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: swarm.swarm_plugin.tasks.add_microservice
